### ISSUE TITLE
Possible Geomag Library Demo and Test Page Typo

### ISSUE THREAD

**Issue by 185driver** [cmweiss/geomagJS#3]
Thanks so much for this handy resource.

Technically not an issue found in this repository, but I noticed something on the related Geomag Library Demo and Test page (http://cmweiss.github.io/geomagjs/geomag.htm). On line 189 of the source code, the text mentions re: variation that "negative values are east". I believe it should be that "positive", not "negative" values are east. True? Thanks again.

**Comment by cmweiss** [comment]
Investigating....
