### ISSUE TITLE
Results differ with various local timezones

### ISSUE THREAD

**Issue by wallw-bits** [cmweiss/geomagJS#4]
Edit:
The root cause of this was found in https://github.com/cmweiss/geomagJS/issues/4#issuecomment-355418074 near the end of this thread.

---

Thanks for making such a useful library!

We are experiencing different numerical results when using this library on Ubuntu versus OS X and RHEL 7.

Here are the steps to reproduce (assuming NodeJS is installed):

1. make a temp dir and cd to it
2. `curl 'https://raw.githubusercontent.com/cmweiss/geomagJS/master/newGeomag.js' -o geomag.js`
3. Edit that file so that it has `module.exports = function Geomag(...` so node can pick it up
4. `curl 'https://raw.githubusercontent.com/cmweiss/geomagJS/master/WMM.COF' -o WMM.COF`
5. Drop this test file in
```
'use strict';

const Geomag = require('./geomag.js');
const fs = require('fs');

var file = fs.readFileSync('./WMM.COF', 'UTF-8');
var gm = new Geomag(file);

var date = new Date(1488386496470);
var precision = 1E-8

var sets = [{
  coord: [5, 10],
  bearing: 42.99295488826924,
  expected: 44.22244309187904
}, {
  coord: [5, 10],
  bearing: 44.14439180550811, 
  expected: 45.37388000911791
}, {
  coord: [-50, 80],
  bearing: 72.03828683714403,
  expected: 112.16177561564162
}, {
  coord: [-50, 80],
  bearing: 149.74888585793278,
  expected: 189.87237463643038
}];

var error = false;
sets.forEach((item) => {
  var result = item.bearing - gm.calc(item.coord[1], item.coord[0], undefined, date).dec;
  result = result < 0 ? result + 360 : result;

  if (Math.abs(result - item.expected) > precision) {
    console.log('whoops: ', result, ' was expected as ', item.expected);
    error = true;
  }
});

if (!error) {
  console.log('Test passed!');
}
```
6. run `node <testFile>`

Running this in Ubuntu 14.04, 16.04, and 17.10 produces:
```
whoops:  44.222366214530524  was expected as  44.22244309187904
whoops:  45.37380313176939  was expected as  45.37388000911791
whoops:  112.16118943404994  was expected as  112.16177561564162
whoops:  189.87178845483868  was expected as  189.87237463643038
```

Running our unit tests (from which that test script is derived), produces the same results in Firefox and Chrome. They work in OS X and RHEL 7, but fail with the same values shown above in Ubuntu.

Here's the Dockerfile I was using to run the tests:
```
FROM ubuntu
RUN set -ex; \
    apt-get update; \
    apt-get install -y openjdk-8-jre curl git; \
    curl -sL https://deb.nodesource.com/setup_8.x | bash; \
    apt-get install -y nodejs
```

This is honestly one of the weirder things I have ever seen. It does not appear to be an issue with the underlying system itself as all of our other unit tests with heavy calculations (and much tighter precisions) are passing on all systems. Any help or suggestions would be greatly appreciated.

**Comment by cmweiss** [comment]
Thank you for your report. I don't have any immediate good ideas and I'd very much like to understand the cause of this.
I'd like this to be a collaborative process in which I play a part but in which, for the most part, I expect you to carry the ball as you are able.

As for me:
I don't have a docker environment set up. I'll look into setting it up to replicate your results.
I have this algorithm in python under the same name, geomag, that produces similarly near but not exact results. I don't know the cause of this either. If we can figure out what's going on here that might provide insight into what's going on there.

Keep in mind:
This algorithm can't provide results with more significant figures that the input values. The WMM.COF does not use more than six significant figures. At a glance, your results are the same to five significant figures. The bug exists as long as this one significant figure is missing.

News:
I'm no longer happy with the direction I was going with newGeomag. I prefer the original geomag and I intend to drop newGeomag.

Further:
Since geomag and newGeomag share so much code I expect the same bug in both. Can you confirm this?

Thanks again!

**Comment by wallw-bits** [comment]
Regardless of significant digits of input, I would expect the 64bit Number implementation in Javascript to produce the same results out past that precision. However, the geomag file does not appear to exhibit the same issues. We will switch over to that from the other.

Thanks for your assistance!

**Comment by wallw-bits** [comment]
Also, quick question, is this the correct way to get a magnetic bearing?
```js
var result = item.bearing - gm.calc(item.coord[1], item.coord[0], undefined, date).dec;
```
It struck me as a little odd that the declination was not added to the true north bearing.

**Comment by wallw-bits** [comment]
@cmweiss, I was unfortunately under the impression that the issue was fixed due to the fact that my NodeJS test passed. However, I'm still seeing issues when running it in Chrome and Firefox on that system.

Here's a gist of the test file: https://gist.github.com/wallw-bits/0c0aab1776646faf8fc89968764f6e90

And I'm running these commands in a docker container running Ubuntu 17.10:
```
mkdir -p /workspace
curl -sL https://gist.githubusercontent.com/wallw-bits/0c0aab1776646faf8fc89968764f6e90/raw/feb0c35a36ec5f01af1f5506ceffe8fc847e7298/geomag.test.html -o /workspace/test.html
google-chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9234 --enable-logging --v=2 --user-data-dir=/tmp/chrome file:///workspace/test.html
```

Output:
```
[0104/202950.777969:INFO:CONSOLE(16)] "whoops:  44.222366214530524  was expected as  44.22244309187904", source: file:///workspace/test/test.html (16)
[0104/202950.778699:INFO:CONSOLE(16)] "whoops:  45.37380313176939  was expected as  45.37388000911791", source: file:///workspace/test/test.html (16)
[0104/202950.778944:INFO:CONSOLE(16)] "whoops:  112.16118943404994  was expected as  112.16177561564162", source: file:///workspace/test/test.html (16)
[0104/202950.779541:INFO:CONSOLE(16)] "whoops:  189.87178845483868  was expected as  189.87237463643038", source: file:///workspace/test/test.html (16)
```

That test file passes on OS X.

**Comment by cmweiss** [comment]
I'm not an expert on 64bit math but this strongly suggests to me that different implementations and instances can arrive at different results. I'm reminded of canvas fingerprinting which detects differences among browser instances. I could very well be wrong; that it has nothing to do with this.
Again, thank you for reporting this but as I've said, I currently have no answers for this behavior. Try changing your precision value to 1E-6 from 1E-8 as the WMM.COF does not provide for a precision greater than 1E-6.

**Comment by wallw-bits** [comment]
Were that the case, we would have numerous other unit tests failing. All other calculations are coming out the same outside of this library.

Also, changing the precision to 1E-6 still fails all of those tests.

**Comment by cmweiss** [comment]
What ideas do you have to resolve the problem?

**Comment by wallw-bits** [comment]
Found it. It has nothing to do with Ubuntu. Rather, the issue is timezones (the Ubuntu containers use UTC). The `new Date(year, 0)` in `decimalDate()` returns different values depending on the locally configured timezone. Any created dates should be in whatever timezone the WMM.COF file is in (which I presume to be UTC).

**Comment by cmweiss** [comment]
So, new Date(1488386496470) returns something different depending on the local timezone?

**Comment by wallw-bits** [comment]
That works fine. The `new Date(2017, 0)` version of the constructor returns Jan 1 _local time_, which varies the resulting `valueOf`. See https://github.com/cmweiss/geomagJS/pull/5 for details.

**Comment by cmweiss** [comment]
I like your pull request but before I merge it I'd like you to make one small change. The month param of Date.UTC() is required even though some interpreters allow it to be optional so please change it to Date.UTC(year, 0).

**Comment by wallw-bits** [comment]
Done.

**Comment by cmweiss** [comment]
Thank you for fixing this :)

**Comment by cmweiss** [comment]
Regarding your question on the correct way to get a magnetic bearing:
I wrote this for flight planning so I think in terms of heading....
Magnetic heading = True heading - declination
True heading = Magnetic heading + declination
For example, where I live the declination is about 11 deg West of True North or about -11 as calculated by geomag. If I want to fly 360 True I need to head 011 per my compass.
So:
360 - (-11) = 371 or 11 deg
It can be hard to keep straight and I've just spend at least 15 minutes writing this and correcting signs and confirming.
